version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: lean_users
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    env_file:
      - .env
volumes:
  pg_data: